/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  publicPath: '/myst_assets_folder/',
  serverBuildPath: 'api/index.js',
  serverMainFields: ['main', 'module'],
  serverModuleFormat: 'cjs',
  serverPlatform: 'node',
  serverMinify: false,
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === 'development' ? undefined : './server.js',
  ignoredRouteFiles: ['**/.*'],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    'bail',
    'is-plain-obj',
    'trough',
    'zwitch',
    'nanoid',
    /^vfile.*/,
    'myst-common',
    'myst-to-react',
    'myst-demo',
    '@myst-theme/providers',
    '@myst-theme/icons',
    '@myst-theme/site',
    '@myst-theme/jupyter',
    '@myst-theme/frontmatter',
    'react-syntax-highlighter',
    '@jupyterlab/rendermime',
    '@jupyterlab/rendermime-interfaces',
  ],
  watchPaths: ['../../packages/**/*'],
  future: {
    v2_routeConvention: true,
    v2_normalizeFormMethod: true,
    v2_headers: true,
  },
};
