name: Build Book Theme and Release

on:
  push:
    tags:
      - "v*"
      - "latest"
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: bun install
      - run: bun run build
      - run: bun run test
      - run: make build-book

      # Compress the directory into a ZIP file before uploading
      - name: Compress production artifacts
        run: zip -r book-theme.zip .deploy/book

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-theme
          path: book-theme.zip

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # The tag that triggered the workflow
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: book-theme.zip # Update to point to the ZIP file
          asset_name: book-theme.zip # The name of the uploaded asset
          asset_content_type: application/zip
